In [170]:
import sys
import numpy as np

f_tag = open("toy_index_to_tag.txt",'r')
tag = f_tag.readlines()
tag_dict = {}
for i in range(len(tag)):
    tag_dict[tag[i].strip('\n')] = i+1
print(tag_dict)

{'A': 1, 'B': 2}


In [171]:
f_word = open("toy_index_to_word.txt",'r')
word = f_word.readlines()
word_dict = {}
for i in range(len(word)):
    word_dict[word[i].strip('\n')] = i+1
#print(word_dict)

In [172]:
f_input = open("toytrain.txt",'r')
input = f_input.readlines()
traindata = []
for i in range(len(input)):
    sentence = input[i].strip('\n')
    word = sentence.split(' ')
    traindata.append(word)

splitdata = []
for i in range(len(traindata)): 
    sentence_line = []
    for j in range(len(traindata[i])):
        word_line = []
        splitword = traindata[i][j].split('_')[0]
        splittag = traindata[i][j].split('_')[1]
        word_line.append(splitword)
        word_line.append(splittag)
        sentence_line.append(word_line)
        
    splitdata.append(sentence_line)
print(splitdata)
    

[[['you', 'B'], ['eat', 'A'], ['fish', 'B']], [['you', 'B'], ['fish', 'B'], ['eat', 'A']], [['eat', 'A'], ['fish', 'B']]]


In [173]:
for i in range(len(splitdata)):
    for j in range(len(splitdata[i])):
        splitdata[i][j][0] = word_dict.get(splitdata[i][j][0])
        splitdata[i][j][1] = tag_dict.get(splitdata[i][j][1])
        
#print(splitdata)
            

In [174]:
# find pi initial
pi_count = np.zeros((len(tag_dict), 1))
pi =  np.zeros((len(tag_dict), 1))
for m in range(len(splitdata)):
    pi_count[splitdata[m][0][1] - 1, 0] += 1
pi_count += 1
#print(pi_count)
for i in range(len(tag_dict)):
    pi[i][0] = np.float64(pi_count[i][0]/np.sum(pi_count))

print(pi)

[[0.4]
 [0.6]]


In [175]:
# Matrix A transition
A_count = np.zeros((len(tag_dict), len(tag_dict)))
A = np.zeros((len(tag_dict), len(tag_dict)))

for i in range(len(splitdata)):
    for j in range(len(splitdata[i]) - 1):
            A_count[splitdata[i][j][1] - 1, splitdata[i][j + 1][1] - 1] += 1
            
A_count = A_count + 1
#print(A_count)

for i in range(len(tag_dict)):
    for j in range(len(tag_dict)):
        A[i][j] = np.float64(A_count[i][j]/np.sum(A_count[i]))
        
print(A)
        

[[0.25 0.75]
 [0.6  0.4 ]]


In [176]:
# Matrix B emission
B_count = np.zeros((len(tag_dict), len(word_dict)))
B = np.zeros((len(tag_dict), len(word_dict)))

for i in range(len(splitdata)):
    for j in range(len(splitdata[i])):
            B_count[splitdata[i][j][1] - 1, splitdata[i][j][0] - 1] += 1
            
B_count = B_count + 1
#print(B_count)

for i in range(len(tag_dict)):
    for j in range(len(word_dict)):
        B[i][j] = np.float64(B_count[i][j]/np.sum(B_count[i]))
        
print(B)

[[0.16666667 0.66666667 0.16666667]
 [0.375      0.125      0.5       ]]


In [ ]:
prior = open("hmmprior.txt",'w')
prior.write(pi)

emit = open("emit.txt",'w')
emi.write(B)

trans = open("hmmtrans.txt",'w')
trans.write(A)